version: '3.8'
services:
    notification:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: sh -c "npm install && npm run serve"
        ports:
            - '3000:3000'
        environment:
            NODE_ENV: development
        volumes:
            - '.:/app'
        env_file: .env